# Generated by Django 3.2.6 on 2021-08-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='type_of_home',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('Above 3BHK', 'Above 3BHK'), ('Garden', 'Garden'), ('Villa/Bunglow', 'Villa/Bunglow'), ('Office', 'Office')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
