# Generated by Django 3.2.6 on 2021-08-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aadhaar', models.CharField(default='0', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('profession', models.CharField(choices=[('Garden_cleaner', 'Garden_cleaner'), ('Electrician', 'Electrician'), ('Kitchen_cleaner', 'Kitchen_cleaner'), ('Painter', 'Painter'), ('Home_cleaner', 'Home_cleaner')], max_length=20)),
                ('experience', models.IntegerField()),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
